subComm: &subComm
  type: http
  udp: true
  interval: 86400
  proxy: DIRECTLY
  lazy: true
  health-check:
    enable: true
    # https://cp.cloudflare.com/generate_204
    # http://latency-test.skk.moe/endpoint
    url: http://www.gstatic.com/generate_204
    interval: 600
    timeout: 5 # ç§’
    lazy: true
    expected-status: '204'
    method: HEAD

subAll: &subAll # **æ‰€æœ‰è®¢é˜…ç»„å¼•ç”¨**
  use:
    - s1
    - s2

subMain: &subMain # **ä¸»ç”¨è®¢é˜…ç»„å¼•ç”¨**
  use:
    - s1

# **å„ç§ä»£ç†æä¾›è€…ï¼ˆæœºåœºï¼‰çš„è®¢é˜…é…ç½®**
proxy-providers:
  s1:
    url: ''
    path: ./proxy_provider/s1.yaml
    lazy: true
    <<: *subComm
    override:
      additional-prefix: 's1 Â»'

  s2:
    url: ''
    path: ./proxy_provider/s2.yaml
    <<: *subComm
    override:
      additional-prefix: 's2 Â»'

# **=============================== èŠ‚ç‚¹ä¿¡æ¯ ===============================**
proxies:
  - { name: DIRECTLY, type: direct, udp: true }

# **=============================== DNS é…ç½® ===============================**
dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:1053
  prefer-h3: true # å¦‚æœDNSæœåŠ¡å™¨æ”¯æŒDoH3ä¼šä¼˜å…ˆä½¿ç”¨h3ï¼Œæå‡æ€§èƒ½
  respect-rules: true # è®© DNS è§£æéµå¾ª Clash çš„è·¯ç”±è§„åˆ™
  cache-algorithm: arc # ä½¿ç”¨æ€§èƒ½æ›´ä¼˜çš„ ARC ç¼“å­˜ç®—æ³•ï¼Œé»˜è®¤ lru
  cache-size: 2048 # é™åˆ¶ç¼“å­˜å¤§å°ï¼Œé¿å…å ç”¨è¿‡å¤šå†…å­˜

  use-hosts: true # ä½¿ç”¨hosts
  use-system-hosts: true # ä½¿ç”¨ç³»ç»Ÿhosts

  # å¯ç”¨ Fake-IP æ¨¡å¼ï¼Œè¿™æ˜¯å¼ºåˆ¶åŠ«æŒæ‰€æœ‰ DNS è¯·æ±‚çš„å…³é”®ã€‚
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  # Fake-IP è¿‡æ»¤å™¨ï¼šç¡®ä¿å›½å†…åŸŸåä¸è¢« Fake-IP è½¬æ¢ã€‚
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - 'geosite:connectivity-check'
    - 'geosite:private'
    - 'rule-set:fake_ip_filter_DustinWin'

  default-nameserver:
    - 223.5.5.5 # é˜¿é‡Œï¼ˆå›½å†…ï¼‰
    - 119.29.29.29 # è…¾è®¯ï¼ˆå›½å†…ï¼‰

  # é»˜è®¤ DNS, ä¾›æ‰€æœ‰è¯·æ±‚ä½¿ç”¨
  nameserver:
    - https://223.5.5.5/dns-query#h3=true
    - https://dns.alidns.com/dns-query
    - https://223.5.5.5/dns-query
    - https://doh.pub/dns-query
    # - 223.5.5.5
    # - 119.29.29.29

  nameserver-policy:
    'geosite:cn,private': # å›½å†…åŸŸåå’Œç§æœ‰åŸŸåå¼ºåˆ¶èµ°å›½å†… DNS
      - https://223.5.5.5/dns-query#h3=true
      - https://dns.alidns.com/dns-query
      - https://223.5.5.5/dns-query
    'geo:cn':
      - https://223.5.5.5/dns-query#h3=true
      - https://dns.alidns.com/dns-query
      - https://223.5.5.5/dns-query

  # ç”¨äºä»£ç†æœåŠ¡å™¨è‡ªèº«çš„ DNS è§£æ
  proxy-server-nameserver:
    - https://223.5.5.5/dns-query
    - 223.5.5.5
    - 119.29.29.29

# **æ§åˆ¶é¢æ¿**
external-controller: 127.0.0.1:9090
secret: '123456.'
external-ui: './ui'
external-ui-url: 'https://github.com/Zephyruso/zashboard/releases/latest/download/dist.zip'

# **=============================== å…¨å±€è®¾ç½® ===============================**
# å½±å“å…¨å±€ç½‘ç»œå’Œç³»ç»Ÿçš„é…ç½®
# è®¾ç½®ä»£ç†ç›‘å¬çš„ç«¯å£ã€ç³»ç»Ÿå‚æ•°ç­‰
# æ§åˆ¶ä»£ç†å¦‚ä½•ä¸ç³»ç»Ÿäº¤äº’
port: 7890
socks-port: 7891 # SOCKS5 ä»£ç†ç«¯å£
mixed-port: 7892 # HTTP(S) å’Œ SOCKS ä»£ç†æ··åˆç«¯å£
allow-lan: true # å…è®¸å±€åŸŸç½‘è¿æ¥
mode: rule
bind-address: '*' # ç»‘å®š IP åœ°å€ï¼Œä»…ä½œç”¨äº allow-lan ä¸º trueï¼Œ'*'è¡¨ç¤ºæ‰€æœ‰åœ°å€
ipv6: true
unified-delay: true # æ›´æ¢å»¶è¿Ÿè®¡ç®—æ–¹å¼ï¼Œå»é™¤æ¡æ‰‹ç­‰é¢å¤–å»¶è¿Ÿ
tcp-concurrent: true # å¯ç”¨ TCP å¹¶å‘è¿æ¥ã€‚è¿™å…è®¸ Clash åŒæ—¶å»ºç«‹å¤šä¸ª TCP è¿æ¥ï¼Œå¯ä»¥æé«˜ç½‘ç»œæ€§èƒ½å’Œè¿æ¥é€Ÿåº¦
log-level: warning # æŸ¥ä¸œè¥¿æ—¶æ”¹æˆinfo
find-process-mode: 'strict' # è®¾ç½®è¿›ç¨‹æŸ¥æ‰¾æ¨¡å¼ä¸ºä¸¥æ ¼æ¨¡å¼ï¼ŒClash ä¼šæ›´ç²¾ç¡®åœ°è¯†åˆ«å’ŒåŒ¹é…ç½‘ç»œæµé‡æ¥æºçš„è¿›ç¨‹
global-client-fingerprint: chrome # è®¾ç½®å…¨å±€å®¢æˆ·ç«¯æŒ‡çº¹ä¸º Chromeï¼Œä½¿ Clash åœ¨å»ºç«‹è¿æ¥æ—¶æ¨¡æ‹Ÿ Chrome æµè§ˆå™¨çš„ TLS æŒ‡çº¹ï¼Œå¢å¼ºéšç§æ€§å’Œç»•è¿‡æŸäº›ç½‘ç«™çš„æŒ‡çº¹æ£€æµ‹
keep-alive-idle: 600
keep-alive-interval: 15
disable-keep-alive: false

profile:
  # è®°å¿†é€‰æ‹©
  store-selected: true
  store-fake-ip: true

# **=============================== TUN é…ç½® ===============================**
# é…ç½® TUN æ¨¡å¼ï¼Œé€‚ç”¨äºé€æ˜ä»£ç†å’Œé«˜æ•ˆæµé‡è½¬å‘
tun:
  enable: false
  stack: mixed # system/gvisor/mixed
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
  strict-route: true # é¿å…å†—ä½™è·¯ç”±æ±¡æŸ“ç³»ç»Ÿè¡¨
  dns-hijack:
    - any:53
    - tcp://any:53
  mtu: 1500 # å‡å°‘ MTU é—®é¢˜ï¼Œå¦‚ç½‘é¡µæ— æ³•æ‰“å¼€ã€æµ‹é€Ÿæ…¢
  gso: true # å¯ç”¨é€šç”¨åˆ†æ®µå¸è½½ï¼ˆæå‡æ€§èƒ½ï¼‰
  gso-max-size: 65536
  udp-timeout: 300 # UDP ä¼šè¯ä¿æŒæ—¶é—´

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports:
        - 80
        - 8080-8880
      override-destination: true
    TLS:
      ports:
        - 443
        - 8443
    QUIC:
      ports:
        - 443
        - 8443
  force-domain:
    - +.v2ex.com
  skip-domain:
    - Mijia Cloud
    - +.push.apple.com
  skip-src-address:
    - 192.168.1.1/24
    - 192.168.66.1/24
  skip-dst-address:
    - 91.105.192.0/23
    - 91.108.4.0/22
    - 91.108.8.0/21
    - 91.108.16.0/21
    - 91.108.56.0/22
    - 95.161.64.0/20
    - 149.154.160.0/20
    - 185.76.151.0/24
    - 2001:67c:4e8::/48
    - 2001:b28:f23c::/47
    - 2001:b28:f23f::/48
    - 2a0a:f280:203::/48

# **=============================== GEO æ•°æ®åº“é…ç½® ===============================**
# è¯¥é…ç½®ç”¨äºåŠ è½½åœ°ç†ä½ç½®ä¿¡æ¯æ•°æ®åº“ï¼ŒåŒ…æ‹¬ IP å’ŒåŸŸåçš„åœ°ç†ä½ç½®æ•°æ®
# åœ¨ä¸åŒçš„è§„åˆ™é…ç½®ä¸­ï¼Œå¯ä»¥ä½¿ç”¨åœ°ç†ä¿¡æ¯è¿›è¡Œæ›´ç²¾ç¡®çš„æµé‡è·¯ç”±

# GEO æ•°æ®åº“æ¨¡å¼é…ç½®ï¼Œå¯ç”¨è¯¥åŠŸèƒ½ä»¥è·å–å’Œä½¿ç”¨åœ°ç†ä½ç½®ä¿¡æ¯
geodata-mode: true

# GEO æ•°æ®åº“åŠ è½½æ¨¡å¼ï¼Œé€‰æ‹©åˆé€‚çš„å†…å­˜å ç”¨ç­–ç•¥
# 'memconservative' é€‚ç”¨äºè¾ƒä½å†…å­˜å ç”¨ï¼Œä¿è¯ç³»ç»Ÿæ€§èƒ½
geodata-loader: standard

# æ˜¯å¦è‡ªåŠ¨æ›´æ–° GEO æ•°æ®åº“ï¼Œé»˜è®¤æ¯48å°æ—¶æ›´æ–°ä¸€æ¬¡
geo-auto-update: true
# GEO æ•°æ®åº“æ›´æ–°é—´éš”æ—¶é—´ï¼Œå•ä½ä¸ºå°æ—¶
geo-update-interval: 48

# GEO æ•°æ®åº“æ–‡ä»¶ä¸‹è½½åœ°å€é…ç½®ï¼Œæä¾›å„ç±» GEO æ•°æ®æ–‡ä»¶çš„ URLï¼Œç¡®ä¿å®æ—¶æ›´æ–°
geox-url:
  geoip: 'https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.dat'
  geosite: 'https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat'
  mmdb: 'https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.metadb'
  asn: https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb

# **=============================== ä»£ç†ç»„è®¾ç½® ===============================**
# ä»£ç†ç»„ç”¨äºç®¡ç†ä¸åŒä»£ç†çš„åˆ†ç±»å’Œè°ƒåº¦ç­–ç•¥
# æ³¨æ„é”šç‚¹å¿…é¡»æ”¾åœ¨å¼•ç”¨çš„ä¸Šæ–¹ï¼Œå¯ä»¥é›†ä¸­æŠŠé”šç‚¹å…¨éƒ¨æ”¾yamlçš„é¡¶éƒ¨ã€‚

FilterHK: &FilterHK '(?=.*(ğŸ‡­ğŸ‡°|æ¸¯|HK|(?i)Hong))^((?!(æ—¥|å¡|ç‹®|ç¾)).)*$'
FilterJP: &FilterJP '(?=.*(ğŸ‡¯ğŸ‡µ|(?<!å°¼)æ—¥|JP|(?i)Japan))^((?!(æ¸¯|å¡|ç‹®|ç¾)).)*$'
FilterSG: &FilterSG '(?=.*(ğŸ‡¸ğŸ‡¬|å¡|ç‹®|ç…|SG|(?i)Singapore))^((?!(æ¸¯|æ—¥|ç¾)).)*$'
FilterUS: &FilterUS '(?=.*(ğŸ‡ºğŸ‡¸|ç¾|US|(?i)States|American))^((?!(æ¸¯|æ—¥|å¡|ç‹®)).)*$'

UrlTest: &urltest
  type: url-test
  interval: 6
  tolerance: 20
  lazy: true
  # url: http://latency-test.skk.moe/endpoint
  url: http://www.gstatic.com/generate_204
  disable-udp: false
  timeout: 2000
  max-failed-times: 3
  hidden: false
FallBack: &fallback
  type: fallback
  interval: 6
  lazy: true
  url: http://www.gstatic.com/generate_204
  disable-udp: false
  timeout: 2000
  max-failed-times: 3
  hidden: false
LoadBalance:
  type: load-balance
  interval: 6
  lazy: true
  url: http://www.gstatic.com/generate_204
  disable-udp: false
  strategy: consistent-hashing
  timeout: 2000
  max-failed-times: 3
  hidden: false

# **ä»£ç†ç»„**
proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - å°æ¹¾æ•…è½¬
      - æ—¥æœ¬æ•…è½¬
      - é¦™æ¸¯è‡ªåŠ¨
      - æ—¥æœ¬è‡ªåŠ¨
      - æ—¥æœ¬èŠ‚ç‚¹
      - å…¨éƒ¨èŠ‚ç‚¹
    icon: 'https://raw.githubusercontent.com/Mithcell-Ma/icon/refs/heads/main/Manual_Test_Log.png'

  # AI ä¸»ç­–ç•¥ç»„ï¼šæ‰‹åŠ¨é€‰æ‹©å…¥å£
  - name: AI
    type: select
    proxies:
      - ç¾å›½èŠ‚ç‚¹
    icon: 'https://github.com/DustinWin/ruleset_geodata/releases/download/icons/ai.png'

  - name: å°æ¹¾æ•…è½¬
    <<: *subMain
    type: fallback
    interval: 6
    lazy: true
    url: http://www.gstatic.com/generate_204
    disable-udp: false
    timeout: 2000
    max-failed-times: 3
    hidden: false
    filter: '(?i)(å°æ¹¾|TW)'
    icon: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/icon/color/asn.png'
  - name: æ—¥æœ¬æ•…è½¬
    <<: *subMain
    type: fallback
    interval: 6
    lazy: true
    url: http://www.gstatic.com/generate_204
    disable-udp: false
    timeout: 2000
    max-failed-times: 3
    hidden: false
    filter: '(?i)(ğŸ‡¯ğŸ‡µ|æ—¥æœ¬|æ±äº¬|ä¸œäº¬|JP|japan|tokyo|osaka)'
    icon: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/icon/color/asn.png'

  - name: é¦™æ¸¯è‡ªåŠ¨
    <<: *subMain
    type: url-test
    interval: 6
    tolerance: 20
    lazy: true
    # url: http://latency-test.skk.moe/endpoint
    url: http://www.gstatic.com/generate_204
    disable-udp: false
    timeout: 2000
    max-failed-times: 3
    hidden: false
    filter: "(?i)(é¦™æ¸¯|hk|ğŸ‡­ğŸ‡°|hong\\s?kong)"
    icon: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/release/icon/color/auto.png'
  - name: æ—¥æœ¬è‡ªåŠ¨
    <<: *subMain
    type: url-test
    interval: 6
    tolerance: 20
    lazy: true
    # url: http://latency-test.skk.moe/endpoint
    url: http://www.gstatic.com/generate_204
    disable-udp: false
    timeout: 2000
    max-failed-times: 3
    hidden: false
    filter: '(?i)(ğŸ‡¯ğŸ‡µ|æ—¥æœ¬|æ±äº¬|ä¸œäº¬|JP|japan|tokyo|osaka)'
    icon: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/release/icon/color/auto.png'

  # ğŸ“º åª’ä½“å¹³å°
  - {
      name: YouTube,
      hidden: true,
      type: select,
      <<: *subMain,
      icon: 'https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/YouTube.png',
    }

  - {
      name: Speedtest,
      hidden: true,
      type: select,
      proxies: [DIRECTLY, Proxy],
      icon: 'https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Speedtest.png',
    }
  - {
      name: Trackerslist,
      hidden: true,
      type: select,
      proxies: [DIRECTLY, Proxy],
      icon: 'https://github.com/DustinWin/ruleset_geodata/releases/download/icons/trackerslist.png',
    }

  # ğŸŒ åŒºåŸŸèŠ‚ç‚¹ç›´é€‰ï¼ˆä¾› UI æ‰‹åŠ¨åˆ‡æ¢ï¼‰
  - {
      name: ç¾å›½èŠ‚ç‚¹,
      type: select,
      <<: *subAll,
      skip-cert-verify: true,
      include-all: true,
      filter: "(?i)(ğŸ‡ºğŸ‡¸|ç¾å›½|US|united\\s?states|america|usa|æ´›æ‰çŸ¶|è¾¾æ‹‰æ–¯|New\\s?York|è¥¿é›…å›¾)",
      icon: 'https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/United_States.png',
    }
  - {
      name: æ—¥æœ¬èŠ‚ç‚¹,
      type: select,
      <<: *subAll,
      skip-cert-verify: true,
      include-all: true,
      filter: '(?i)(ğŸ‡¯ğŸ‡µ|æ—¥æœ¬|æ±äº¬|ä¸œäº¬|JP|japan|tokyo|osaka)',
      icon: 'https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Japan.png',
    }

  - {
      name: å…¨éƒ¨èŠ‚ç‚¹,
      type: select,
      <<: *subAll,
      icon: 'https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/World_Map.png',
      include-all: true,
      filter: '(?i)^((?!(DIRECTLY|DIRECT|Proxy|Traffic|Expire|Expired|è¿‡æœŸ|å‰©ä½™|æµé‡|å®˜ç½‘|è¶…æ—¶|timeout|å¤±æ•ˆ|Invalid|Test|æµ‹é€Ÿ|æœ¬åœ°|Local)).)*$',
    }
  - {
      name: æ¼ç½‘ä¹‹é±¼,
      type: select,
      proxies: [DIRECTLY, Proxy],
      icon: 'https://testingcf.jsdelivr.net/gh/aihdde/Rules@master/icon/fish.png',
    }

# **=============================== è§„åˆ™è®¾ç½® ===============================**
rules:
  # å±è”½ QUIC
  - AND,(AND,(DST-PORT,443),(NETWORK,UDP)),(NOT,((GEOSITE,cn))),REJECT
  - AND,(AND,(DST-PORT,443),(NETWORK,UDP)),(NOT,((GEOIP,CN))),REJECT
  - DOMAIN-SUFFIX,2022822.xyz,DIRECTLY
  - DOMAIN-SUFFIX,download.nvidia.com,DIRECTLY
  # --- æ‹’ç»/é˜»æ­¢ç±»è§„åˆ™ (æœ€é«˜ä¼˜å…ˆçº§ï¼Œç›´æ¥æ‹¦æˆª) ---
  # è¿™äº›è§„åˆ™ä¸æ¶‰åŠ DNS è§£æï¼Œç›´æ¥æ‹’ç»ï¼Œåº”æ”¾åœ¨æœ€å‰é¢ï¼Œä»¥é˜»æ­¢ä¸å¿…è¦çš„æµé‡ã€‚
  - RULE-SET,AWAvenue_Ads_Rule,REJECT # ç§‹é£å¹¿å‘Šè¿‡æ»¤

  - RULE-SET,telegram_ip,Proxy,no-resolve
  - RULE-SET,Telegram_No_Resolve,Proxy,no-resolve
  - PROCESS-NAME-REGEX,.*telegram.*,Proxy
  - RULE-SET,telegram_domain,Proxy

  - GEOSITE,private,DIRECT
  - GEOSITE,category-public-tracker,DIRECT
  - GEOSITE,category-games@cn,DIRECT
  - GEOSITE,apple@cn,DIRECT
  - GEOSITE,icloud,DIRECT
  - GEOSITE,microsoft@cn,DIRECT
  - GEOSITE,onedrive,DIRECT
  - GEOSITE,microsoft,Proxy
  - GEOSITE,telegram,Proxy
  - GEOSITE,category-ai-!cn,AI
  # ====== IP =======
  - GEOIP,telegram,Proxy,no-resolve
  # - GEOIP,netflix,Netflix,no-resolve
  - GEOIP,private,DIRECT,no-resolve

  - RULE-SET,ai,AI
  - RULE-SET,youtube_domain,YouTube
  - RULE-SET,speedtest_domain,Speedtest

  # Sukka çš„è§„åˆ™é›†
  - RULE-SET,global_non_ip,Proxy
  - RULE-SET,skk_direct,DIRECT
  - RULE-SET,domestic_non_ip,DIRECT
  - RULE-SET,domestic_ip,DIRECT,no-resolve
  - RULE-SET,china_ip,DIRECT,no-resolve
  - RULE-SET,china_ip_ipv6,DIRECT,no-resolve
  # - RULE-SET,cdn_domainset,Proxy
  # - RULE-SET,cdn_non_ip,Proxy

  - RULE-SET,proxy,Proxy
  - RULE-SET,gfw_domain,Proxy

  - DOMAIN-SUFFIX,cn,DIRECT
  - RULE-SET,blackmatrix7_direct,DIRECTLY
  # è‹¹æœæœåŠ¡ç›´è¿ (macOS)
  # - DOMAIN-SUFFIX,apple.com,DIRECTLY
  # - DOMAIN-SUFFIX,icloud.com,DIRECTLY
  # - DOMAIN-SUFFIX,cdn-apple.com,DIRECTLY # é’ˆå¯¹è‹¹æœCDNåŠ é€Ÿ
  # - DOMAIN-SUFFIX,ls.apple.com,DIRECTLY # é’ˆå¯¹ Apple å®šä½ï¼Œç›´è¿è§„åˆ™

  # --- Tracker / BT ä¸‹è½½ (ç‰¹æ®Šæµé‡ï¼Œä¼˜å…ˆçº§è¾ƒä½) ---
  - RULE-SET,trackerslist,Trackerslist

  # --- æœ€ç»ˆå›é€€è§„åˆ™ (æœ€ä½ä¼˜å…ˆçº§ï¼Œæ•è·æ‰€æœ‰æœªåŒ¹é…æµé‡) ---
  - GEOIP,CN,DIRECT
  - MATCH,æ¼ç½‘ä¹‹é±¼

# **=============================== è§„åˆ™æä¾›è€… ===============================**
# **ruleå¼•ç”¨è®¾ç½®**
Classical: &classical
  type: http
  behavior: classical
  interval: 86400
Domain: &domain
  type: http
  behavior: domain
  interval: 86400
IP: &ip
  type: http
  behavior: ipcidr
  interval: 86400

# **åŠ¨æ€åŠ è½½è§„åˆ™é…ç½®ï¼Œæä¾›å®æ—¶æ›´æ–°çš„è§„åˆ™é›†åˆ**
rule-providers:
  # å¹¿å‘Šè¿‡æ»¤
  AWAvenue_Ads_Rule:
    {
      <<: *domain,
      format: yaml,
      path: ./ruleset/AWAvenue_Ads_Rule_Clash.yaml,
      url: 'https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main//Filters/AWAvenue-Ads-Rule-Clash.yaml',
    }
  # fake-ip è¿‡æ»¤
  fake_ip_filter_DustinWin:
    {
      <<: *domain,
      format: mrs,
      path: ./ruleset/fake_ip_filter_DustinWin.mrs,
      url: 'https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/fakeip-filter.mrs',
    }

  # skk è§„åˆ™
  skk_direct:
    <<: *classical
    format: text
    path: ./rule-providers/direct.txt
    url: https://ruleset.skk.moe/Clash/non_ip/direct.txt
  global_non_ip:
    <<: *classical
    format: text
    path: ./rule-providers/global_non_ip.txt
    url: https://ruleset.skk.moe/Clash/non_ip/global.txt
  cdn_domainset:
    <<: *domain
    format: text
    path: ./rule-providers/cdn_domainset.txt
    url: https://ruleset.skk.moe/Clash/domainset/cdn.txt
  cdn_non_ip:
    <<: *classical
    format: text
    path: ./rule-providers/cdn_non_ip.txt
    url: https://ruleset.skk.moe/Clash/non_ip/cdn.txt
  domestic_non_ip:
    <<: *classical
    format: text
    path: ./rule-providers/domestic_non_ip.txt
    url: https://ruleset.skk.moe/Clash/non_ip/domestic.txt
  domestic_ip:
    <<: *classical
    format: text
    path: ./rule-providers/domestic_ip.txt
    url: https://ruleset.skk.moe/Clash/ip/domestic.txt
  china_ip:
    <<: *ip
    format: text
    path: ./rule-providers/china_ip.txt
    url: https://ruleset.skk.moe/Clash/ip/china_ip.txt
  china_ip_ipv6:
    <<: *ip
    format: text
    path: ./rule-providers/china_ip_ipv6.txt
    url: https://ruleset.skk.moe/Clash/ip/china_ip_ipv6.txt
  download_domainset:
    <<: *domain
    format: text
    url: https://ruleset.skk.moe/Clash/domainset/download.txt
    path: ./rule_set/sukkaw_ruleset/download_domainset.txt
  download_non_ip:
    <<: *domain
    format: text
    url: https://ruleset.skk.moe/Clash/non_ip/download.txt
    path: ./rule_set/sukkaw_ruleset/download_non_ip.txt

  # ç›´è¿ç±»è§„åˆ™
  blackmatrix7_direct:
    {
      <<: *domain,
      format: yaml,
      path: ./ruleset/blackmatrix7_direct.yaml,
      url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Direct/Direct.yaml',
    }
  private_domain:
    {
      <<: *domain,
      format: mrs,
      path: ./ruleset/private_domain.mrs,
      url: 'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs',
    }
  cn_domain:
    {
      <<: *domain,
      format: mrs,
      path: ./ruleset/cn_domain.mrs,
      url: 'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs',
    }
  # BT ä¸‹è½½éšç§ç±»
  trackerslist:
    {
      <<: *domain,
      format: mrs,
      path: ./ruleset/trackerslist.mrs,
      url: 'https://github.com/DustinWin/ruleset_geodata/raw/refs/heads/mihomo-ruleset/trackerslist.mrs',
    }

  # ä»£ç†ç±»è§„åˆ™
  proxy:
    {
      <<: *domain,
      format: mrs,
      path: ./ruleset/proxy.mrs,
      url: 'https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/proxy.mrs',
    }
  gfw_domain:
    {
      <<: *domain,
      format: mrs,
      path: ./ruleset/gfw_domain.mrs,
      url: 'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/gfw.mrs',
    }
  ai:
    {
      <<: *domain,
      format: mrs,
      path: ./ruleset/ai,
      url: 'https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/ai.mrs',
    }
  youtube_domain:
    {
      <<: *domain,
      format: mrs,
      path: ./ruleset/youtube_domain.mrs,
      url: 'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs',
    }
  # Telegram
  telegram_domain:
    {
      <<: *classical,
      format: yaml,
      path: ./ruleset/telegram_domain.yaml,
      url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.yaml',
    }
  telegram_ip:
    {
      <<: *ip,
      format: mrs,
      path: ./ruleset/telegram_ip.mrs,
      url: 'https://github.com/DustinWin/ruleset_geodata/raw/refs/heads/mihomo-ruleset/telegramip.mrs',
    }
  Telegram_No_Resolve:
    {
      <<: *classical,
      format: yaml,
      path: ./ruleset/Telegram_No_Resolve.yaml,
      url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Telegram/Telegram_No_Resolve.yaml',
    }
  speedtest_domain:
    {
      <<: *domain,
      format: mrs,
      path: ./ruleset/speedtest_domain.mrs,
      url: 'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/ookla-speedtest.mrs',
    }
